from pyjarowinkler import JaroDistanceError as JaroDistanceError

__DEFAULT_DECIMALS__: int
__DEFAULT_SCALING__: float
__MAX_PREFIX_LENGTH__: int

def get_jaro_similarity(first: str, second: str, *, decimals: int = ..., ignore_case: bool = False) -> float: ...
def get_jaro_distance(first: str, second: str, *, decimals: int = ..., ignore_case: bool = False) -> float: ...
def get_jaro_winkler_similarity(first: str, second: str, *, scaling: float = ..., decimals: int = ..., ignore_case: bool = False) -> float: ...
def get_jaro_winkler_distance(first: str, second: str, *, scaling: float = ..., decimals: int = ..., ignore_case: bool = False) -> float: ...
