on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: lint-and-test-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
      - run: uvx ruff check --diff
      - run: uvx ruff format --diff

  test:
    name: python-${{ matrix.python-version }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: python-${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: uvx --with 'coverage[toml]' coverage run -m unittest discover -s tests/
      - run: uvx --with 'coverage[toml]' coverage report

  package:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
      - run: uv build --verbose
      - id: uv
        run: echo "package_version=$(uv version --short | tr -d '\n')" >> "${GITHUB_OUTPUT}"
      - uses: actions/upload-artifact@v4
        with:
          name: pyjarowinkler-${{ steps.uv.outputs.package_version }}
          path: dist/pyjarowinkler-*
          if-no-files-found: error
          overwrite: true
